---
# TODO(goldilocks): add network policies
# TODO(goldilocks): add securityContext
# TODO(goldilocks): gvisor
# TODO(linkerd)
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: goldilocks
      version: 6.1.2
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 5m
  timeout: 20m
  values:
    controller:
      resources:
        requests:
          cpu: 15m
          memory: 145M
        limits:
          memory: 174M

    dashboard:
      replicaCount: 1
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          memory: 64M

      ingress:
        enabled: true
        ingressClassName: "ambassador"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: ingress.${INGRESS_DOMAIN}

        hosts:
          - host: &host "goldilocks.${CLUSTER_NAME}.${INGRESS_DOMAIN}"
            paths:
              - path: /
                type: Prefix

        tls:
          - secretName: tls.goldilocks
            hosts:
              - *host
