---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cilium
spec:
  interval: 1h0m0s
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: cilium
      version: ">=1.10.3 <1.11.0"
      sourceRef:
        kind: HelmRepository
        name: cilium
  install:
    crds: CreateReplace
  values:
    hubble:
      metrics:
        enabled:
          - tcp
          - flow
          - icmp
          - http
          - drop
          - dns:query;ignoreAAAA
        serviceMonitor:
          enabled: true
    containerRuntime:
      integration: auto
    prometheus:
      enabled: false
      serviceMonitor:
        enabled: false
        namespace: "monitoring"
    resourceQuotas:
      enabled: true