---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-certmanager
  namespace: flux-system
spec:
  dependsOn:
    - name: kyverno-base
  interval: 1h
  path: "./kubernetes/clusters/home/apps/cert-manager/base"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-certmanager-config
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-certmanager
  interval: 1h
  path: "./kubernetes/clusters/home/manifests/cert-manager/config"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
