---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: linkerd-namespace
  namespace: flux-system
spec:
  interval: 1h
  path: "./kubernetes/clusters/home/manifests/network/linkerd/namespace"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: linkerd-certs
  namespace: flux-system
spec:
  dependsOn:
    - name: linkerd-namespace
    - name: cert-manager-certmanager
  interval: 1h
  path: "./kubernetes/clusters/home/manifests/network/linkerd/certificate"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
spec:
  dependsOn:
    - name: kyverno-base
    - name: linkerd-namespace
    - name: linkerd-certs
  interval: 1h
  path: "./kubernetes/clusters/home/manifests/network/linkerd"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
