---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  dependsOn:
    - name: vault
    - name: linkerd
  interval: 1h
  path: "./kubernetes/clusters/home/apps/database/postgres"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
