---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno-base
  namespace: flux-system
spec:
  interval: 1h
  path: "./kubernetes/clusters/home/apps/security/kyverno/base"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  dependsOn:
    - name: kyverno-base
  interval: 1h
  path: "./kubernetes/clusters/home/apps/security/kyverno/policies"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secrets-csi-driver
  namespace: flux-system
spec:
  interval: 1h
  path: "./kubernetes/clusters/home/apps/security/secrets-csi-driver"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  dependsOn:
    - name: linkerd
    - name: rook-ceph-cluster
  interval: 1h
  path: "./kubernetes/clusters/home/apps/security/vault/base"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
