---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph-namespace
  namespace: flux-system
spec:
  interval: 1h
  path: "./kubernetes/clusters/home/apps/storage/rook-ceph/namespace"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: rook-ceph-namespace
  interval: 1h
  path: "./kubernetes/clusters/home/apps/storage/rook-ceph/operator"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: rook-ceph-namespace
    - name: rook-ceph-operator
  interval: 1h
  path: "./kubernetes/clusters/home/apps/storage/rook-ceph/cluster"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph-addons
  namespace: flux-system
spec:
  dependsOn:
    - name: rook-ceph-namespace
    - name: rook-ceph-operator
    - name: rook-ceph-cluster
  interval: 1h
  path: "./kubernetes/clusters/home/apps/storage/rook-ceph/add-ons"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
