---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: descheduler
  namespace: flux-system
spec:
  interval: 1h
  path: "./kubernetes/clusters/home/apps/system/descheduler"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: descheduler
  namespace: flux-system
spec:
  interval: 1h
  path: "./kubernetes/clusters/home/apps/system/node-feature-discovery"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 1h
  path: "./kubernetes/clusters/home/apps/system/reloader"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 1h
  path: "./kubernetes/clusters/home/apps/system/kubelet-service-cert-approver"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1h
  path: "./kubernetes/clusters/home/apps/system/metrics-server"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
