---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vpn-namespace
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/clusters/home/apps/vpn/namespace"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vpn-downloads-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: vpn-namespace
  interval: 5m
  path: "./kubernetes/clusters/home/apps/vpn/downloads-gateway"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
