---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-deployment
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/clusters/home/flux/deploy
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
