---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: rook-release
spec:
  interval: 1h0m0s
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: rook-ceph
      version: ">=v1.7.1 <v2.0.0"
      sourceRef:
        kind: HelmRepository
        name: rook-release
  install:
    crds: CreateReplace
