---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: rook
spec:
  interval: 30m0s
  ref:
    semver: ">=v1.7.1 <v2.0.0"
  url: https://github.com/rook/rook
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rook-cluster
spec:
  interval: 1h0m0s
  targetNamespace: rook-ceph
  path: ./cluster/examples/kubernetes/ceph/cluster.yaml
  prune: true
  dependsOn:
    - namespace: monitoring
      name: kube-prometheus-stack
  sourceRef:
    kind: GitRepository
    name: rook
  patchesStrategicMerge:
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      spec:
        mon:
          count: 1
        monitoring:
          enabled: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rook-block-pool
spec:
  interval: 1h0m0s
  targetNamespace: rook-ceph
  path: ./cluster/examples/kubernetes/ceph/pool.yaml
  prune: true
  dependsOn:
    - name: rook-cluster
  sourceRef:
    kind: GitRepository
    name: rook
  patchesStrategicMerge:
    - apiVersion: ceph.rook.io/v1
      kind: CephBlockPool
      metadata:
        name: replicapool
      spec:
        replicated:
          size: 1
          requireSafeReplicaSize: false
