---
#TODO(vault): add network policies
#TODO(vault): add security context
#TODO(vault): add prometheus scraping role
#TODO(vault): add log aggregation
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: vault
      version: 0.20.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    standalone:
      enabled: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "file" {
          path = "/vault/data"
        }
    dataStorage:
      storageClass: "ceph-block"
    csi:
      enabled: true
