---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 1h
  chart:
    spec:
      chart: metallb
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
      interval: 1h
  values:
    existingConfigMap: "metallb-config"
    controller:
      securityContext:
        runAsNonRoot: true
        # nobody
        runAsUser: 65534
        fsGroup: 65534
        readOnlyRootFilesystem: true
    prometheus:
      podMonitor:
        enabled: false
      prometheusRule:
        enabled: false
    speaker:
      tolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
      frr:
        enabled: true
        image:
          repository: docker.io/frrouting/frr
          tag: v8.2.2
