---
# TODO(ceph-cluster): fix storage node reference
# TODO(ceph-cluster): network rules
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.9.2
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  values:
    toolbox:
      enabled: false

    monitoring:
      enabled: true
      createPrometheusRules: true

    configOverride: |
      [global]
      bdev_enable_discard = true
      bdev_async_discard = true

    cephClusterSpec:
      cephVersion:
        image: quay.io/ceph/ceph:v17.2.0

      # TODO(rook-ceph): Enable host network on next rebuild
      network:
        provider: host
      # TODO(rook-ceph): Enable compression on next rebuild
      connections:
        compression:
          enabled: true

      resources:
        mgr:
          requests:
            cpu: "125m"
            memory: "549M"
          limits:
            memory: "1219M"
        mon:
          requests:
            cpu: "49m"
            memory: "477M"
          limits:
            memory: "1059M"
        osd:
          requests:
            cpu: "442m"
            memory: "2678M"
          limits:
            memory: "5944M"
        prepareosd:
          requests:
            cpu: "250m"
            memory: "50Mi"
          limits:
            memory: "200Mi"
        mgr-sidecar:
          requests:
            cpu: "49m"
            memory: "94M"
          limits:
            memory: "208M"
        crashcollector:
          requests:
            cpu: "15m"
            memory: "64M"
          limits:
            memory: "64M"
        logcollector:
          requests:
            cpu: "100m"
            memory: "100M"
          limits:
            memory: "1G"
        cleanup:
          requests:
            cpu: "250m"
            memory: "100M"
          limits:
            memory: "1G"

      crashCollector:
        disable: false

      dashboard:
        enabled: true
        urlPrefix: /

      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
          - name: "delta"
            devices:
              - name: "/dev/disk/by-id/nvme-Samsung_SSD_980_1TB_S649NX0RB57009Y"
          - name: "enigma"
            devices:
              - name: "/dev/disk/by-id/nvme-Samsung_SSD_980_1TB_S649NX0RB57050E"
          - name: "felix"
            devices:
              - name: "/dev/disk/by-id/nvme-CT1000P1SSD8_202228759489"

    ingress:
      ingressClassName: ambassador
      dashboard:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: ingress.${INGRESS_DOMAIN}
          linkerd.io/inject: enabled
        host:
          name: "rook.${CLUSTER_NAME}.${INGRESS_DOMAIN}"
          path: "/"
        tls:
          - secretName: tls.rook-ceph
            hosts:
              - "rook.${CLUSTER_NAME}.${INGRESS_DOMAIN}"

    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: csi-rbdplugin-snapclass

    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            imageFormat: "2"
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4

    cephFileSystems:
      - name: ceph-filesystem
        spec:
          metadataPool:
            replicated:
              size: 3
          dataPools:
            - failureDomain: host
              replicated:
                size: 3
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              requests:
                cpu: "35m"
                memory: "64M"
              limits:
                memory: "144M"
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-filesystem
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          mountOptions: []
          parameters:
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4

    cephObjectStores:
      - name: ceph-objectstore
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: 3
          dataPool:
            failureDomain: host
            erasureCoded:
              dataChunks: 2
              codingChunks: 1
          preservePoolsOnDelete: true
          gateway:
            port: 80
            resources:
              requests:
                cpu: 1000m
                memory: 1Gi
              limits:
                memory: 2Gi
            instances: 1
          healthCheck:
            bucket:
              interval: 60s
        storageClass:
          enabled: true
          name: ceph-bucket
          reclaimPolicy: Delete
          parameters:
            region: us-east-1
