---
# TODO(descheduler): add network policies
# TODO(descheduler): add security context
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: descheduler
      version: 0.23.2
      sourceRef:
        kind: HelmRepository
        name: descheduler-charts
        namespace: flux-system
      interval: 1h
  values:
    kind: Deployment
    replicas: 3

    leaderElection:
      enabled: true

    podAnnotations:
      configmap.reloader.stakater.com/reload: "descheduler"

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 143M

    deschedulerPolicy:
      strategies:
        RemoveDuplicates:
          enabled: true

        RemovePodsViolatingNodeTaints:
          enabled: true

        RemovePodsViolatingNodeAffinity:
          enabled: true
          params:
            nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution

        RemovePodsViolatingTopologySpreadConstraint:
          enabled: true
          params:
            includeSoftConstraints: true

        RemovePodsViolatingInterPodAntiAffinity:
          enabled: true
          params:
            nodeFit: true

        LowNodeUtilization:
          enabled: false

        RemoveFailedPods:
          enabled: true
          params:
            failedPods:
              includingInitContainers: true
              excludeOwnerKinds:
                - "Job"
              minPodLifetimeSeconds: 3600

        RemovePodsHavingTooManyRestarts:
          enabled: true
          params:
            podsHavingTooManyRestarts:
              podRestartThreshold: 100
              includingInitContainers: true
