---
# TODO(external-dns): add network policies
# TODO(external-dns): add security context

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: external-dns
      version: 1.7.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
  values:
    crd:
      create: true
    provider: cloudflare
    policy: sync
    txtPrefix: "k8s."

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 64M
    serviceMonitor:
      enabled: true
    extraArgs:
      - --source=ingress
      - --cloudflare-proxied
      - --annotation-filter=external-dns/is-pulic=true
      - --domain-filters=${INGRESS_DOMAIN}
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-secrets
            key: api_token
      - name: CF_API_EMAIL
        value: ${EMAIL_1}
