apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secrets
    namespace: external-dns
stringData:
    api_token: ENC[AES256_GCM,data:626SUYdQhoGQOYA0rT+ScaDHwI4wFb8S73zZov+8Seu3PdhNGUGlkA==,iv:aA8mTBsjPVgVcfXVqXdNQkf4Su+9H/fFsralI7eb1gk=,tag:xqF+AfGePzJma30rUKkIqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13exjdp7pdsct3lh7j339tyvchhzprgqqk383gqtl6wsecmvrls3sn7fets
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSzNPUzBYendCSnMzelRm
            S2JsZm5WUHg0ZTgyaGoyK3dKOUJTSCtZQUhZCmxwTE90WkdzRm1sTDdOZ3dWeThy
            aWlpd25wQXBKRlZzbjBJTW5qc3kyVlkKLS0tIFpwK2IrOW9wa0swdlhUM3c2V3pD
            eFZNYUlFZC9vdEFHR1VXSHp6UW9BMzQKiG2FJ+Fws4pqwnzkn8HQiXxf+FBz/CrH
            amwc4wsb4VNMp36D5V9nNQfEpftVpMb78n9qvqzaMqV6a5IlvTXNwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-18T16:39:47Z"
    mac: ENC[AES256_GCM,data:MfD3vuRK2h2Keumrc3kShZlH9TUrTtanamSUBDIZpUwjjf2lPn7QU9sZglEdO7GwYAWPYbSeFytAHtUu3rfCYQW968hUqx49XsmexkuPZwsezmkvCBFAxTpajzq7MGfY/6k0SwBi2DupjbPh2qfQHWbNggNtsOc0i2jns70xPJQ=,iv:65W9YjrsiATz2TAtQih+3vPZPj5aASWuHGrdvQVJsj4=,tag:EG2VzVlgVkCx+GTAAkeFJA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData|email|domains))
    version: 3.7.2
