grafana:
  enabled: false
  sidecar:
    dashboards:
      searchNamespace: ALL

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    additionalPodMonitors:
      - name: fluxcd
        joblabel: 'fluxcd'
        namespaceSelector:
          matchNames:
            - flux-system
        selector:
          matchLabels:
            app.kubernetes.io/part-of: flux