---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-crds
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: kyverno-crds
      version: ">=2.0.0 <3.0.0"
      sourceRef:
        kind: HelmRepository
        name: kyverno
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
