---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kyverno-policies
spec:
  dependsOn:
    - name: kyverno-crds
  interval: 1h0m0s
  path: "./kyverno/policies/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
