---
# TODO(grafana): add network policies
# TODO(grafana): add security policies
# TODO(gvisor): use gvisor for all front end pods
# TODO(grafana): add linkerd inject annotation to pod
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.29.2
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  timeout: 20m
  values:
    replicas: 1
    deploymentStrategy:
      type: Recreate

    image:
      repository: ghcr.io/k8s-at-home/grafana

    env:
      GF_EXPLORE_ENABLED: true
      GF_PANELS_DISABLE_SANITIZE_HTML: true
      GF_LOG_FILTERS: rendering:debug
      GF_DATE_FORMATS_USE_BROWSER_LOCALE: true

    admin:
      existingSecret: grafana-secrets
      userKey: adminUser
      passwordKey: adminPass

    grafana.ini:
      server:
        root_url: "http://grafana.${CLUSTER_NAME}.${INGRESS_DOMAIN}"
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      analytics:
        check_for_updates: false
      log:
        mode: console
      grafana_net:
        url: https://grafana.net
      auth.basic:
        disable_login_form: false

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default

    datasources:
      datasources.yaml:
        apiVersion: 1
        deleteDatasources:
          - name: Loki
            orgId: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://thanos-query.monitoring:9090/
            access: proxy
            isDefault: true
          - name: Loki
            type: loki
            access: proxy
            url: http://loki.monitoring:3100

    dashboards:
      default:
        node-exporter-full:
          url: https://grafana.com/api/dashboards/1860/revisions/22/download
          datasource: Prometheus

    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL

    imageRenderer:
      enabled: true

    plugins:
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - grafana-piechart-panel
      - vonage-status-panel
      - grafana-worldmap-panel
      - grafana-clock-panel

    serviceMonitor:
      enabled: true

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns.alpha.kubernetes.io/target: ingress.${INGRESS_DOMAIN}
      ingressClassName: nginx
      hosts:
        - &host "grafana.${CLUSTER_NAME}.${INGRESS_DOMAIN}"
      tls:
        - secretName: grafana-${CLUSTER_NAME}-tls
          hosts:
            - *host

    persistence:
      enabled: false

    resources:
      requests:
        cpu: 23m
        memory: 110M
      limits:
        memory: 152M

    podAnnotations:
      configmap.reloader.stakater.com/reload: "grafana"
