---
# TODO(postgresql): add network policies
# TODO(postgresql): add security context
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  interval: 1h
  chart:
    spec:
      chart: postgresql
      version: 11.2.6
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 1h
  values:
    metrics:
      enabled: true
      image:
        registry: public.ecr.aws
        repository: bitnami/postgres-exporter
      serviceMonitor:
        enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 32M
        limits:
          # cpu: 15m
          memory: 34M
    commonAnnotations:
      prometheus.io/probe: "true"
      prometheus.io/protocol: "tcp"
    image:
      registry: public.ecr.aws
      repository: bitnami/postgresql
    architecture: standalone
    primary:
      persistence:
        storageClass: "ceph-block"
    auth:
      username: root
      existingSecret: "postgres-secrets"
