---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: kyverno
spec:
  interval: 1h0m0s
  dependsOn:
    - name: kyverno
  chart:
    spec:
      chart: kyverno-policies
      version: 2.3.4
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  values:
    podSecurityStandard: restricted
