---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  interval: 1h
  chart:
    spec:
      chart: reloader
      version: v0.0.110
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
      interval: 1h
  values:
    resources:
      requests:
        cpu: 15m
        memory: 184M
      limits:
        memory: 184M
    deployment:
      containerSecurityContext:
        capabilities:
          drop:
            - ALL
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true

    podMonitor:
      enabled: true
      namespace: monitoring
