---
# TODO(speed): network policies
# TODO(speed): Security Context
# TODO(linkerd)
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: speedtest-exporter
      version: 5.3.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 1hs
  values:
    image:
      repository: ghcr.io/miguelndecarvalho/speedtest-exporter
      tag: v3.5.1
    env:
      TZ: America/New York
    metrics:
      enabled: true
    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 64M
