---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-repositories
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/clusters/home/flux/repositories
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
  decryption:
    provider: sops
    secretRef:
      name: sops-age
