---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-crds
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-config
    - name: cluster-repositories
    - name: manage-flux
  interval: 10m0s
  path: ./kubernetes/clusters/home/crds
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops
  decryption:
    provider: sops
    secretRef:
      name: sops-age
