apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: authentik-database
  namespace: authentik
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    roleName: "authentik"
    objects: |
      - objectName: "postgres-pass"
        secretPath: "database/creds/authentik"
        secretKey: "password"
      - objectName: "postgres-user"
        secretPath: "database/creds/authentik"
        secretKey: "username"
