---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: actions-runner-controller
spec:
  interval: 1m
  url: https://actions-runner-controller.github.io/actions-runner-controller
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-system
spec:
  interval: 5m
  chart:
    spec:
      chart: actions-runner-controller
      version: actions-runner-controller-0.12.7
    sourceRef:
      kind: HelmRepository
      name: actions-runner-controller
    interval: 1m
    dependsOn:
      - name: cert-manager
        namespace: cert-manager
    install:
      createNamespace: true
  valuesFrom:
    - kind: Secret
      name: github-actions-creds
