---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - transformer.yaml
namespace: actions-runner-system
resources:
  - actions-runner-release.yml
  - namespace.yml

secretGenerator:
  - name: github-actions-creds
    behavior: create
    files:
      - values.yaml=actions-runner-creds.yml
