---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actions-runner-system
resources:
  - actions-runner-release.yml
  - namespace.yml

secretGenerator:
  - name: github-actions-creds
    files:
      - values.yaml=secrets.actions-runner-creds.yml
