---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: github-runners
spec:
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: RunnerDeployment
  interval: 1h0m0s
  path: "./actions-runner/github-runners/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
