---
# TODO(secrets-csi): add logging
# TODO(secrets-csi): add network rules
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
  namespace: kube-system
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: vault
      version: 0.20.0
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
        namespace: flux-system
  values:
    syncSecret:
      enabled: true
    enableSecretRotation: true
