---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cert-manager
spec:
  interval: 1h0m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: cert-manager
      version: ">=v1.4.0 <v2.0.0"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 1h0m0s
  values:
    installCRDs: true
    prometheus:
      enabled: false
